- hosts: windows
  roles:
    - papel_de_parede_e_icones_lab             
  gather_facts: yes
  tasks:
    - win_chocolatey:
        name: 
        - procexp
        - git 
        - googlechrome
        - flashplayerplugin
        - jre8
        - firefox
        - 7zip.install
        - notepadplusplus.install
        - vlc # player de video
        - winscp.portable
        - ghostscript.app  # base para cutepdf
        - cutepdf # impressora PDF
        - foxitreader # leitor PDF
        - codeblocks
        - geogebra-classic.install
        - scilab
        - python
        - scenebuilder9  
        - r
        - r.studio  
        - virtualbox
        - virtualbox-guest-additions-guest.install
        - winmerge 
        - k-litecodecpackmega # pacote de drivers
        - gimp # editor de imagens
        - inkscape  #editor de vetores
        - vscode
        - pdfsam.install # unir PDF 
        state: present

    - win_chocolatey:
            name: pdfxchangeeditor
            install_args: 
            - /NoUpdater 
              #            - /NoViewInBrowsers
            state: absent
    - win_chocolatey:
            name: mysql.workbench
            state: present
    - win_chocolatey:
            name: arduino
            state: present
    - win_chocolatey:
            name: cmaptools
            state: present

            #    - name: Change the hostname to sample-hostname
            #      win_hostname:
            #        name: somente-teste
            #      register: res

            #    - name: Reboot
            #      win_reboot:
            #      when: res.reboot_required
