- name: alterar hostname computadores windows
  debug:
    msg: "ip: {{ item.ip }} hostname {{ item.hostname }}"
  with_items:
          - { ip: 192.168.15.21, hostname: gw-c221 }
          - { ip: 192.168.15.22, hosrname: gw-c222 } 

